version: '3'

services:
  traefik:
    image: traefik:v2.10
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/etc/traefik/traefik.yml"  # Traefik configuration
      - "./maintenance:/maintenance"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    labels:
      # Define middleware for the maintenance plugin
      - "traefik.http.middlewares.maintenance-plugin.plugin.traefik-maintenance.enabled=true"
      - "traefik.http.middlewares.maintenance-plugin.plugin.traefik-maintenance.filename=/maintenance/maintenance.html"
      - "traefik.http.middlewares.maintenance-plugin.plugin.traefik-maintenance.triggerFilename=/maintenance/maintenance.trigger"
      - "traefik.http.middlewares.maintenance-plugin.plugin.traefik-maintenance.httpResponseCode=503"
      - "traefik.http.middlewares.maintenance-plugin.plugin.traefik-maintenance.httpContentType=text/html; charset=utf-8"

  # Web application service
  webapp:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`webapp.172.31.105.210.nip.io`)"
      - "traefik.http.routers.webapp.entrypoints=web"
      # Attach maintenance-plugin middleware
      - "traefik.http.routers.webapp.middlewares=maintenance-plugin"
